# Generated by Django 6.0 on 2025-12-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('location', models.CharField(verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус активности')),
            ],
        ),
    ]
