# Generated by Django 6.0 on 2025-12-09 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_category_description_alter_product_created_at_and_more'),
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Поступление'), ('OUT', 'Списание'), ('MOVE', 'Перемещение'), ('ADJUST', 'Настройка')], help_text='Тип действия', max_length=20, verbose_name='Тип действия')),
                ('quantity', models.IntegerField(verbose_name='Изменение кол-ва')),
                ('reference', models.CharField(max_length=255, verbose_name='Действие')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Товар')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.storage', verbose_name='Склад')),
            ],
        ),
    ]
