# Generated by Django 6.0 on 2025-12-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_created_at'),
        ('products', '0002_category_description_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.product', verbose_name='Товар'),
        ),
    ]
